version: '3'
services:
  craftfinder:
    image: rust:latest
    container_name: craftfinder
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: hackerpassword
      POSTGRES_DB: craftfinder_db
      POSTGRES_PORT: 5432
      DATABASE_URL: postgresql://postgres:hackerpassword@postgres:5432/craftfinder_db
    command: cargo run --bin server
    ports:
      - "3000:3000"
  craftfinder-fe:
    image: rust:latest
    container_name: craftfinder-fe
    volumes:
      - ./:/app
    working_dir: /app/frontend
    command: bash -c "rustup target add wasm32-unknown-unknown && cargo install trunk && cargo install wasm-bindgen-cli && trunk serve --proxy-backend=http://craftfinder:3000/"
    ports:
      - "8080:8080"
  postgres:
    image: postgres:latest
    container_name: postgres
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
    working_dir: /
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: hackerpassword
      POSTGRES_DB: craftfinder_db
    ports:
      - "5432:5432"
