//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "in_group")]
pub enum InGroup {
    #[sea_orm(string_value = "group_a")]
    GroupA,
    #[sea_orm(string_value = "group_b")]
    GroupB,
    #[sea_orm(string_value = "group_c")]
    GroupC,
}
